apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Jenkins Merged Core Service
  creationTimestamp: null
  labels:
    app: jenkins-core
  name: jenkins-core
spec:
  ports:
  - name: jenkins-core-port-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jenkins-core-jni-port-http
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins-core
    deploymentconfig: jenkins-core
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
